### ISSUE TITLE
please give .env file

### ISSUE THREAD

**Issue by Aayush-683** [Brandon-The-Dev/Hydra#2]
can u ples give .env file :D

**Comment by Aayush-683** [comment]
why close :/

**Comment by enlighten1self** [comment]
Make your own .env file. Open notepad and save. Rename to .env I hope you know how to insert tokens... also read license agreement and join the discord. Upvote as wel!

**Comment by Brandon-The-Dev** [comment]
> can u ples give .env file :D

You only need your mongodb and your token
