### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by johntaxmi** [Brandon-The-Dev/Hydra#4]
How can I change the prefix and make it without the need for space?
I tried everything in the message event, changing the args to [0] but still couldn't make it work.

so like how can I change the prefix to `%` and make the commands work with `%help` and not with `% help`

**Comment by Brandon-The-Dev** [comment]
const messageArray = message.content.split(' ');
        const cmd = messageArray[1];
        const args = messageArray.slice(2);
        
Just replace these with how you want it to respond

**Comment by johntaxmi** [comment]
```
const messageArray = message.content.split(' ');
const cmd = messageArray[0];
const args = messageArray.slice(1);
```
        
Shouldn't that work without space? Like `%help` by just moving both 1 argument before?

**Comment by Brandon-The-Dev** [comment]
Have you tried it I can’t really test anything as am not on my pc but just use 

const cmd = messageArray[0];

**Comment by Brandon-The-Dev** [comment]
Don’t think you need the args or the slice when there is no space 👍

**Comment by johntaxmi** [comment]
just tried
```
const messageArray = message.content.substring(prefix.length).split(" ");
const cmd = messageArray[0]
const args = messageArray[1]
```
And now am getting an error on the help command, `Cannot read property 'slice' of undefined`.


Nevermind, made it work. Tried the most commands seem to work perfectly.
Thanks for your time. Have a nice day!
