### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by johntaxmi** [Brandon-The-Dev/Hydra#7]
Make the cooldowns start only when the commands fully get completed and not when there are missing requirements.
For example, if I do the rob command without mentioning somebody don't start the cooldown from then, but start it only when I mention somebody and the command completes.

**Comment by Brandon-The-Dev** [comment]
It’s already been put down for when my pc is fixed 👍 there is a little bug as well but people won’t find it 😂
